services:
  - type: web
    name: edumanage-sms
    env: docker # Changed from php to docker
    plan: free
    region: oregon
    envVars:
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        value: "postgresql://neondb_owner:npg_vx7COHzKsbw6@ep-floral-leaf-aiqqkfcy-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: APP_KEY
        value: "base64:XQs7EMdvY9yJP3Gp7zDuQsrPMRV/E+JJeHbYEWcYCnA="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"